version: '3.8'

services:
  splitwise-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__Splitwise=Server=mysql;Database=Splitwise;User Id=sa;Password=mysql@123

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: Splitwise
      MYSQL_USER: sa
      MYSQL_PASSWORD: mysql@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
